bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from bot import views

app_name = 'bot'
urlpatterns = [
    path('get/', csrf_exempt(views.bot_get), name='get'),
    path('send_tm/', csrf_exempt(views.send_tm), name='send_tm'),
    path('rmv_usr/', views.rmv_usr, name='rmv_usr'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('abd/', views.abd, name='abd')
]

tb12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contest/', include('contest.urls')),
    path('bot/', include('bot.urls')),
]

home/models.py
from django.db import models

home/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import render
from bot.models import BannedWord


def home(request):
    raise Http404


def abd(request):
    if request.method == 'POST':
        BannedWord.objects.get_or_create(word=str(request.POST['word']).strip().lower())
    context = {
        'title': 'banned word',
        'words': BannedWord.objects.all(),
    }
    return render(request, 'home/banned_word.html', context)

templates/home/banned_word.html
{% extends 'base/base.html' %}
{% block content %}
    <div class="container text-white">
        <button class="btn-lg btn-info">Banned word from BRUR NewBees</button>
        <form action="{% url 'home:abd' %}" method="post">
            {% csrf_token %}
            <div class="form-group bg-white text-black-50">
                <label for="word">Add word</label><input type="text" name="word" id="word">
                <button type="submit" class="btn-lg btn-outline-danger">Save</button>
            </div>
        </form>
        {% for word in words %}
        <h4>{{ word.word }}</h4>
        {% endfor %}
    </div>
{% endblock content %}