bot/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from bot import views

app_name = 'bot'
urlpatterns = [
    path('get/', csrf_exempt(views.bot_get), name='get'),
    path('send_tm/', csrf_exempt(views.send_tm), name='send_tm'),
    path('rmv_usr/', views.rmv_usr, name='rmv_usr'),
]

home/urls.py
from django.urls import path
from home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('abd/', views.abd, name='abd')
]

tb12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('contest/', include('contest.urls')),
    path('bot/', include('bot.urls')),
]

templates/base/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>{{ title }}</title>
</head>
<body style="background-color: #1b1e21">

<nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar01"><span
            class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="nav-bar01">
        <a class="font-size25 btn-outline-success text-white nav-item" href="{% url 'home:home' %}">Home</a>
    </div>
</nav>
<!-- Start of different part. This is for home -->

{% block content %}{% endblock content %}
<br>
<br>

<!-- End of different part. This was for home -->
<footer class="fixed-bottom bg-dark text-white row font-weight-bold" size="22">
    <div class="container-fluid row">
        <div class="col-auto">
            <em>Designed by</em> <br>
            <em>Mahmudul Alam</em> <br>
        </div>
    </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>